# Generated by Django 4.2.2 on 2023-07-22 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0005_alter_quest_task_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('min_description', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorldInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('game_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.gameinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FAQTown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_name', models.CharField(max_length=100)),
                ('faq_category', models.CharField(max_length=100)),
                ('faq_description', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.city')),
            ],
        ),
        migrations.CreateModel(
            name='FAQItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_title', models.CharField(max_length=100)),
                ('faq_description', models.TextField()),
                ('item_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.itemcategory')),
            ],
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_title', models.CharField(max_length=100)),
                ('fiq_item_category', models.CharField(max_length=100)),
                ('faq_description', models.TextField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.item')),
            ],
        ),
    ]
