
WIDTH = 20
HEIGHT = 20
MAX_PLAYERS = 4
BEAT_TIME = 1
CHARACTER_TASK_INTERVAL = 60
PLAYER_WIDTH = 10
PLAYER_HEIGHT = 10
MAX_ANIMALS_ON_MAP = 5
# Add more settings as needed
# Диапазон возможных значений для температуры
MIN_TEMPERATURE = -20.00
MAX_TEMPERATURE = 35.00
SLEEP_TIME = 30
CHARACTER_COST_STEP = 1
CHARACTER_COST_BATTLE_WITH_ANIMAL = 5
CHARACTER_COST_BATTLE_PVP = 10
STAMINA_RESTORATION_AMOUNT = 5
