# Generated by Django 4.2.2 on 2023-07-13 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('species', models.CharField(default=None, max_length=100)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=100)),
                ('health_max', models.IntegerField(default=100)),
                ('stamina_max', models.IntegerField(default=100)),
                ('stamina', models.IntegerField(default=100)),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('speed', models.IntegerField(default=10)),
                ('regeneration', models.IntegerField(default=10)),
                ('defense', models.IntegerField(default=10)),
                ('experience', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('race', models.CharField(choices=[('Human', 'Human'), ('Elf', 'Elf'), ('Dwarf', 'Dwarf'), ('Orc', 'Orc'), ('Goblin', 'Goblin'), ('Zombie', 'Zombie'), ('Skeleton', 'Skeleton'), ('Centaur', 'Centaur'), ('Gryphon', 'Gryphon'), ('Nymph', 'Nymph'), ('Vampire', 'Vampire'), ('Gul', 'Gul'), ('Cyborg', 'Cyborg'), ('Robot', 'Robot'), ('Mutant', 'Mutant'), ('Cyborg Elf', 'Cyborg Elf'), ('Goblin Geneticist', 'Goblin Geneticist'), ('Orc Mechanic', 'Orc Mechanic'), ('Humanoids', 'Humanoids')], max_length=255)),
                ('profession', models.CharField(choices=[('Warrior', 'Warrior'), ('The Magician', 'The Magician'), ('Scout', 'Scout'), ('Engineer', 'Engineer'), ('Healer', 'Healer'), ('Merchant', 'Merchant'), ('Artisan', 'Artisan'), ('Traveller', 'Traveller'), ('Researcher', 'Researcher')], default='Warrior', max_length=255)),
                ('health_max', models.IntegerField(default=100)),
                ('mana_max', models.IntegerField(default=100)),
                ('mana', models.IntegerField(default=100)),
                ('stamina_max', models.IntegerField(default=100)),
                ('stamina', models.IntegerField(default=100)),
                ('health', models.IntegerField(default=100)),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('defense', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('energy', models.IntegerField(default=10)),
                ('speed', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
                ('regeneration', models.IntegerField(default=10)),
                ('intuition', models.IntegerField(default=10)),
                ('luck', models.IntegerField(default=10)),
                ('accuracy', models.IntegerField(default=10)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('is_quest_completed', models.BooleanField(default=False)),
                ('last_regeneration', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x_coordinate', models.IntegerField()),
                ('y_coordinate', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CraftsmenSquare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='craftsmen_square', to='game.city')),
            ],
        ),
        migrations.CreateModel(
            name='EntertainmentDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entertainment_district', to='game.city')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('name', models.CharField(default=None, max_length=255)),
                ('passable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PalaceSquare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='palace_square', to='game.city')),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.animal')),
                ('color', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
            ],
            bases=('game.animal',),
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.animal')),
                ('breed', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
            bases=('game.animal',),
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('craftsmen_square', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='game.craftsmensquare')),
            ],
        ),
        migrations.CreateModel(
            name='Tavern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('entertainment_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taverns', to='game.entertainmentdistrict')),
            ],
        ),
        migrations.CreateModel(
            name='RoyalPalace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('palace_square', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='royal_palace', to='game.palacesquare')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('task_model', models.CharField(choices=[('k', 'kill_animal'), ('f', 'find')], max_length=1)),
                ('completed', models.BooleanField(default=False)),
                ('experience_reward', models.IntegerField(default=0)),
                ('objective_quantity', models.PositiveIntegerField(default=0)),
                ('objective_progress', models.PositiveIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='game.character')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='news_photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.category')),
            ],
        ),
        migrations.CreateModel(
            name='MarketSquare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_square', to='game.city')),
            ],
        ),
        migrations.CreateModel(
            name='MarketShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_shop', to='game.marketsquare')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('entertainment_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='game.entertainmentdistrict')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='game.news')),
            ],
        ),
        migrations.CreateModel(
            name='CityManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('palace_square', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='city_management', to='game.palacesquare')),
            ],
        ),
        migrations.CreateModel(
            name='CityGateWest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_gate_west', to='game.city')),
            ],
        ),
        migrations.CreateModel(
            name='CityGateSouth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_gate_south', to='game.city')),
            ],
        ),
        migrations.CreateModel(
            name='CityGateNorth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_gate_north', to='game.city')),
            ],
        ),
        migrations.CreateModel(
            name='CityGateEast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_gate_east', to='game.city')),
            ],
        ),
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('entertainment_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casinos', to='game.entertainmentdistrict')),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.character')),
            ],
        ),
    ]
