# Generated by Django 4.2.2 on 2023-06-21 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('race', models.CharField(choices=[('Human', 'Human'), ('Elf', 'Elf'), ('Dwarf', 'Dwarf')], max_length=255)),
                ('health_max', models.IntegerField(default=100)),
                ('mana_max', models.IntegerField(default=100)),
                ('mana', models.IntegerField(default=100)),
                ('stamina_max', models.IntegerField(default=100)),
                ('stamina', models.IntegerField(default=100)),
                ('health', models.IntegerField(default=100)),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('energy', models.IntegerField(default=10)),
                ('speed', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
                ('regeneration', models.IntegerField(default=10)),
                ('intuition', models.IntegerField(default=10)),
                ('luck', models.IntegerField(default=10)),
                ('accuracy', models.IntegerField(default=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
