# Generated by Django 4.2.2 on 2023-07-20 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.animal')),
                ('color', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
            ],
            bases=('game.animal',),
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.animal')),
                ('breed', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
            bases=('game.animal',),
        ),
        migrations.CreateModel(
            name='RewardItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.animal')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='reward_items',
            field=models.ManyToManyField(blank=True, related_name='reward_items', to='game.rewarditems'),
        ),
    ]
