# Generated by Django 4.2.2 on 2023-07-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='is_quest_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='task_model',
            field=models.CharField(choices=[('k', 'kill_animal'), ('f', 'find')], max_length=100),
        ),
    ]
