# Generated by Django 4.2.2 on 2023-06-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
