# Generated by Django 4.2.2 on 2023-07-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_character_is_quest_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
