# Generated by Django 4.2.2 on 2023-07-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_animal_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='mob_battle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='pvp_battle',
            field=models.IntegerField(default=0),
        ),
    ]
