# Generated by Django 4.2.2 on 2023-07-21 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_animal_reward_items_delete_rewarditems'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.animal')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('animal_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.animalinventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item')),
            ],
        ),
    ]
