# Generated by Django 4.2.2 on 2023-06-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_character_x_character_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='neighbors',
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='location',
            name='passable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
