# Generated by Django 4.2.2 on 2023-06-24 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_location_neighbors_location_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
    ]
