# Generated by Django 4.2.2 on 2023-07-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_character_mob_battle_character_pvp_battle'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='have_quest',
            field=models.BooleanField(default=False),
        ),
    ]
