# Generated by Django 4.2.2 on 2023-06-25 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_location_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('species', models.CharField(default=None, max_length=100)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=100)),
                ('health_max', models.IntegerField(default=100)),
                ('stamina_max', models.IntegerField(default=100)),
                ('stamina', models.IntegerField(default=100)),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('speed', models.IntegerField(default=10)),
                ('regeneration', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.animal')),
                ('color', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
            ],
            bases=('game.animal',),
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.animal')),
                ('breed', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
            bases=('game.animal',),
        ),
    ]
