# Generated by Django 4.2.2 on 2023-07-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_quest_task_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='new_character',
            field=models.BooleanField(default=True),
        ),
    ]
