# Generated by Django 4.2.2 on 2023-07-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_character_have_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
    ]
