# Generated by Django 4.2.2 on 2023-06-30 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_animal_cat_dog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_x', models.IntegerField()),
                ('current_y', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='ai',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.ai'),
        ),
    ]
