# Generated by Django 4.2.2 on 2023-07-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_location_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='river',
            field=models.BooleanField(default=False),
        ),
    ]
