# Generated by Django 4.2.2 on 2023-07-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_character_new_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultilingualText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('text_field_en', models.TextField()),
                ('text_field_uk', models.TextField()),
                ('text_field_ru', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('uk', 'Українська'), ('ru', 'Русский')], max_length=2)),
            ],
        ),
    ]
