# Generated by Django 4.2.2 on 2023-07-16 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_location_lake_location_river'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='quest_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.character'),
        ),
    ]
