# Generated by Django 4.2.2 on 2023-07-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_multilingualtext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultilingualText',
        ),
    ]
