# Generated by Django 4.2.2 on 2023-06-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_ai_character_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai',
            name='current_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ai',
            name='current_y',
            field=models.IntegerField(default=0),
        ),
    ]
