# Generated by Django 4.2.2 on 2023-07-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_multilingualtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='accuracy',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='animal',
            name='charisma',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='animal',
            name='energy',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='animal',
            name='intelligence',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='animal',
            name='intuition',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='animal',
            name='luck',
            field=models.IntegerField(default=10),
        ),
    ]
