# Generated by Django 4.2.2 on 2023-08-02 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_animal_accuracy_animal_charisma_animal_energy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(default='neutral', max_length=10)),
                ('temperature', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('is_in_battle', models.BooleanField(default=False)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai', to='game.character')),
            ],
        ),
    ]
