# Generated by Django 4.2.2 on 2023-08-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_aicharacter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AICharacter',
        ),
    ]
