# Generated by Django 4.2.2 on 2023-07-01 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_actionlog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.character'),
        ),
    ]
