# Generated by Django 4.2.2 on 2023-07-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_actionlog_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='defense',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='defense',
            field=models.IntegerField(default=10),
        ),
    ]
