# Generated by Django 4.2.2 on 2023-08-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_aicharacter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='ai_model_state',
        ),
    ]
